# Generated by Django 2.2 on 2019-04-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
