# Generated by Django 2.1.7 on 2019-04-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190428_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
