# Generated by Django 2.1.7 on 2019-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_article_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaving_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
