# Generated by Django 2.1.7 on 2019-05-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_user_leaving_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=10, verbose_name='主机名')),
                ('port', models.CharField(max_length=4, verbose_name='端口')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞的时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Article', verbose_name='点赞的文章')),
            ],
            options={
                'verbose_name': '文章点赞',
            },
        ),
    ]
