# Generated by Django 2.1.7 on 2019-05-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': '文章点赞', 'verbose_name_plural': '文章点赞'},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='like_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.Likes', verbose_name='点赞人'),
        ),
    ]
