# Generated by Django 2.1.7 on 2019-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20190509_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_user',
        ),
        migrations.AddField(
            model_name='article',
            name='like_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='点赞文章', to='myblog.Likes', verbose_name='点赞人'),
        ),
    ]
