# Generated by Django 2.1.7 on 2019-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20190509_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='Likes_type',
            field=models.CharField(choices=[('article', '文章好'), ('person', '人好')], default='article', max_length=10),
        ),
    ]
