# Generated by Django 2.1.7 on 2019-05-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_likes_likes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Likes_type',
        ),
        migrations.AddField(
            model_name='likes',
            name='likes_type',
            field=models.CharField(choices=[('article', '赞文章'), ('person', '赞作者')], default='article', max_length=10),
        ),
    ]
