# Generated by Django 2.1.7 on 2019-05-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190507_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='expectation',
            options={'ordering': ['-created_time'], 'verbose_name': '我的寄语', 'verbose_name_plural': '我的寄语'},
        ),
        migrations.AlterModelOptions(
            name='leaving',
            options={'ordering': ['-created_time'], 'verbose_name': '我的留言', 'verbose_name_plural': '我的留言'},
        ),
    ]
